pipeline {

    agent any

    stages {
        stage('test1') {
            steps {
	        script {
                  readProperties(file: "migrations/test.properties").each {key, value -> env[key] = value }
                }
                sh './start.sh'
		sh 'pwd'
		sh 'echo $TEST'
		sh 'echo $AZIZ'
            }
        }
        stage('test2') {
	    when {
	        changeset "migrations/*.sh"
	    }
            steps {
                sh 'cd migrations; ./tests.sh'
            }
        }
        stage('test3') {
            steps {
                sh 'echo "Let\'s wrap it up"'
            }
        }
    }
}
