pipeline {

    agent any
    stages {
        stage('test1') {
            steps {
                sh './start.sh'
		sh 'pwd'
		sh 'migrations/tests.sh'
		sh 'echo $JOB_NAME'
		sh 'echo $JOB_BASE_NAME'
            }
        }
        stage('test2') {
	    when {
	        changeset "migrations/*.sh"
	    }
            steps {
                sh 'cd migrations; ./tests.sh'
            }
        }
        stage('test3') {
            steps {
                sh 'echo "Let\'s wrap it up"'
            }
        }
    }
}
